//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InformationManagementBasedOnEvent.rc
//
#define IDD_DIALOG_MAIN                 101
#define IDC_BUTTON_CONSOLE              1001
#define IDC_EDIT_CONSOLE_OUTPUT         1002
#define IDC_EDIT_CONSOLE_INPUT          1003
#define IDC_LIST_STUDENT                1004
#define IDC_BUTTON_STUDENT_LIST_FIRST_PAGE 1005
#define IDC_LIST_COURSE                 1006
#define IDC_RADIO_STUDENT               1007
#define IDC_RADIO_COURSE                1008
#define IDC_BUTTON_FUN_ADD_RANDOM       1010
#define IDC_EDIT_FUN_ADD_WITH_NAME      1011
#define IDC_EDIT_COURSE_LIST_PAGE_NUM   1012
#define IDC_BUTTON_EXIT                 1013
#define IDC_BUTTON_STUDENT_LIST_PREVIOUS_PAGE 1014
#define IDC_BUTTON_STUDENT_LIST_GO_PAGE 1016
#define IDC_BUTTON_STUDENT_LIST_NEXT_PAGE 1017
#define IDC_BUTTON_STUDENT_LIST_LAST_PAGE 1018
#define IDC_BUTTON_COURSE_LIST_FIRST_PAGE 1019
#define IDC_BUTTON_COURSE_LIST_PREVIOUS_PAGE 1020
#define IDC_BUTTON_COURSE_LIST_GO_PAGE  1022
#define IDC_BUTTON_COURSE_LIST_NEXT_PAGE 1023
#define IDC_BUTTON_COURSE_LIST_LAST_PAGE 1024
#define IDC_BUTTON_FUN_ADD_WITH_NAME    1025
#define IDC_BUTTON_FUN_DELETE_CURRENT_SELECTION 1026
#define IDC_BUTTON_FUN_MODIFY_CURRENT_SELECTION 1027
#define IDC_EDIT_FUN_MODIFY_CURRENT_SELECTION 1028
#define IDC_BUTTON_FUN_QUERY_ID         1029
#define IDC_EDIT_FUN_QUERY_ID           1030
#define IDC_BUTTON_FUN_QUERY_NAME       1031
#define IDC_EDIT_FUN_QUERY_NAME         1032
#define IDC_BUTTON19                    1033
#define IDC_BUTTON_FUN_STUDENT_SELECTS_COURSE 1033
#define IDC_BUTTON_FUN_QUERY_CURRENT_SELECTION 1035
#define IDC_EDIT_STUDENT_LIST_PAGE_NUM  1036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
